repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: maven-fmt
        name: Maven Java Formatter
        entry: mvn -P codestyle com.spotify.fmt:fmt-maven-plugin:format
        language: system
        files: \.java$
        pass_filenames: false
