language: java
sudo: false # faster builds

jdk:
# LTS versions
- openjdk8
- openjdk11
- openjdk17

addons:
  sonarcloud:
    organization: "tomdesair-github"

script:
  - mvn clean install -P codestyle
