language: java
sudo: false # faster builds

jdk:
# Latest
- openjdk16
# LTS versions
- openjdk11
- openjdk8

addons:
  sonarcloud:
    organization: "tomdesair-github"

script:
  - mvn clean install -P checkstyle
